<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IRSR8MK" failures="2" tests="3" name="Default test" time="13.96" errors="0" timestamp="17 Oct 2024 11:42:58 GMT">
  <testcase classname="com.adactinhotelapp.TestRunner.AdactinHotelRun" name="printTitle" time="0.028">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Adactin - Hotel Reservation System] but found [Adactin.com - Hotel Reservation System]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Adactin - Hotel Reservation System] but found [Adactin.com - Hotel Reservation System]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.adactinhotelapp.TestRunner.AdactinHotelRun.printTitle(AdactinHotelRun.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- printTitle -->
  <testcase classname="com.adactinhotelapp.TestRunner.AdactinHotelRun" name="printCurrentUrl" time="0.018">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Adactin - Hotel Reservation System] but found [Adactin.com - Hotel Reservation System],
	expected [http://adactinhotelapp.com/] but found [https://adactinhotelapp.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Adactin - Hotel Reservation System] but found [Adactin.com - Hotel Reservation System],
expected [http://adactinhotelapp.com/] but found [https://adactinhotelapp.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.adactinhotelapp.TestRunner.AdactinHotelRun.printCurrentUrl(AdactinHotelRun.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- printCurrentUrl -->
  <testcase classname="com.adactinhotelapp.TestRunner.AdactinHotelRun" name="verifyLogin" time="2.371"/>
</testsuite> <!-- Default test -->
